from fastapi import FastAPI, APIRouter, UploadFile, File, Form, HTTPException, Response, Request
from dotenv import load_dotenv
from starlette.middleware.cors import CORSMiddleware
from motor.motor_asyncio import AsyncIOMotorClient
import os
import re
import logging
import uuid
import asyncio
import requests
from pathlib import Path
from pydantic import BaseModel, Field, ConfigDict
from typing import List, Optional, Any
from datetime import datetime, timezone, timedelta


ROOT_DIR = Path(__file__).parent
load_dotenv(ROOT_DIR / '.env')

# MongoDB connection
mongo_url = os.environ['MONGO_URL']
client = AsyncIOMotorClient(mongo_url)
db = client[os.environ['DB_NAME']]

# Storage configuration
STORAGE_URL = "https://integrations.emergentagent.com/objstore/api/v1/storage"
EMERGENT_KEY = os.environ.get("EMERGENT_LLM_KEY")
APP_NAME = "booktemplate"
storage_key: Optional[str] = None


def init_storage():
    global storage_key
    if storage_key:
        return storage_key
    resp = requests.post(
        f"{STORAGE_URL}/init",
        json={"emergent_key": EMERGENT_KEY},
        timeout=30,
    )
    resp.raise_for_status()
    storage_key = resp.json()["storage_key"]
    return storage_key


def put_object(path: str, data: bytes, content_type: str) -> dict:
    key = init_storage()
    resp = requests.put(
        f"{STORAGE_URL}/objects/{path}",
        headers={"X-Storage-Key": key, "Content-Type": content_type},
        data=data,
        timeout=120,
    )
    resp.raise_for_status()
    return resp.json()


def get_object(path: str):
    key = init_storage()
    resp = requests.get(
        f"{STORAGE_URL}/objects/{path}",
        headers={"X-Storage-Key": key},
        timeout=60,
    )
    resp.raise_for_status()
    return resp.content, resp.headers.get("Content-Type", "application/octet-stream")


MIME_TYPES = {
    "jpg": "image/jpeg",
    "jpeg": "image/jpeg",
    "png": "image/png",
    "gif": "image/gif",
    "webp": "image/webp",
}


# ===== Models =====
def _now_iso():
    return datetime.now(timezone.utc).isoformat()


class Block(BaseModel):
    model_config = ConfigDict(extra="ignore")
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    type: str  # 'text' | 'image'
    x: float = 40
    y: float = 40
    width: float = 300
    height: float = 120
    z_index: int = 1
    # Text block
    html: Optional[str] = ""
    font_family: Optional[str] = "Cormorant Garamond"
    font_size: Optional[int] = 18
    text_align: Optional[str] = "left"
    color: Optional[str] = "#000000"
    # Image block
    image_url: Optional[str] = None
    image_path: Optional[str] = None
    # Chapter heading metadata (text blocks only)
    is_chapter: bool = False
    # Live-sync Table of Contents marker (text blocks only). Blocks with
    # this flag have their html regenerated by the editor whenever chapter
    # blocks change so the TOC always reflects the current chapter list.
    is_toc: bool = False


class Page(BaseModel):
    model_config = ConfigDict(extra="ignore")
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    blocks: List[Block] = []
    background_color: Optional[str] = "#FFF8DC"
    show_page_number: bool = True
    page_number_align: Optional[str] = "right"  # 'left' | 'center' | 'right'
    page_number_size: Optional[int] = 14
    page_number_font: Optional[str] = "Cormorant Garamond"
    full_bleed: bool = False  # when true, ignore the 1cm white margin (edge-to-edge)


class TextPreset(BaseModel):
    model_config = ConfigDict(extra="ignore")
    font_family: Optional[str] = None
    font_size: Optional[int] = None
    text_align: Optional[str] = None
    color: Optional[str] = None


class TextPresets(BaseModel):
    model_config = ConfigDict(extra="ignore")
    title: Optional[TextPreset] = None
    subtitle: Optional[TextPreset] = None
    body: Optional[TextPreset] = None


class Book(BaseModel):
    model_config = ConfigDict(extra="ignore")
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    title: str = "Untitled Book"
    author: Optional[str] = ""
    page_size: str = "a4"  # a4 | letter | square | book6x9
    pages: List[Page] = []
    page_number_start: int = 1  # 1-based; pages before this show no number; back cover always hidden
    is_chapter_book: bool = False  # enables the Add Chapter action and auto-numbered chapter headings
    text_presets: Optional[TextPresets] = None  # per-book overrides for Title/Subtitle/Page-text defaults
    created_at: str = Field(default_factory=_now_iso)
    updated_at: str = Field(default_factory=_now_iso)


class BookCreate(BaseModel):
    title: str = "Untitled Book"
    author: Optional[str] = ""
    page_size: str = "a4"


class BookUpdate(BaseModel):
    model_config = ConfigDict(extra="ignore")
    title: Optional[str] = None
    author: Optional[str] = None
    page_size: Optional[str] = None
    page_number_start: Optional[int] = None
    is_chapter_book: Optional[bool] = None
    text_presets: Optional[TextPresets] = None
    pages: Optional[List[Page]] = None


class BookSummary(BaseModel):
    id: str
    title: str
    author: Optional[str] = ""
    page_size: str
    page_count: int
    created_at: str
    updated_at: str
    cover_image_url: Optional[str] = None
    # Full first-page composition (image blocks + text blocks). Sent so the
    # library can render covers exactly as designed — title + author text
    # layered over the artwork — instead of just the bare image.
    cover_page: Optional[Page] = None


class TemplateStyle(BaseModel):
    model_config = ConfigDict(extra="ignore")
    background_color: Optional[str] = "#FFF8DC"
    full_bleed: bool = False
    show_page_number: bool = True
    page_number_align: Optional[str] = "right"
    page_number_size: Optional[int] = 14


class Template(BaseModel):
    model_config = ConfigDict(extra="ignore")
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    page_size: str = "a4"
    cover: TemplateStyle = Field(default_factory=TemplateStyle)
    interior: TemplateStyle = Field(default_factory=TemplateStyle)
    back_cover: TemplateStyle = Field(default_factory=TemplateStyle)
    text_presets: Optional[TextPresets] = None
    created_at: str = Field(default_factory=_now_iso)


class TemplateCreate(BaseModel):
    name: str
    page_size: str = "a4"
    cover: TemplateStyle
    interior: TemplateStyle
    back_cover: TemplateStyle
    text_presets: Optional[TextPresets] = None



class BookRevision(BaseModel):
    """Lightweight audit-log entry. Stores a full snapshot of the book's
    user-facing state at a moment in time so we can list "saves" and roll
    back when an author wants to recover a previous version."""
    model_config = ConfigDict(extra="ignore")
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    book_id: str
    created_at: str = Field(default_factory=_now_iso)
    title: str = "Untitled Book"
    author: Optional[str] = ""
    page_size: str = "a4"
    page_count: int = 0
    pages: List[Page] = []
    page_number_start: int = 1
    is_chapter_book: bool = False
    text_presets: Optional[TextPresets] = None
    # Human-readable summary derived from the diff against the previous revision.
    summary: str = ""


class BookRevisionSummary(BaseModel):
    id: str
    book_id: str
    created_at: str
    title: str
    page_count: int
    summary: str


# Auto-save fires every ~1.2s during editing. Collapsing those into one
# revision per minute keeps the audit log readable without losing meaningful
# checkpoints.
REVISION_DEBOUNCE_SECONDS = 60
# Per-book cap. Older revisions are trimmed.
REVISION_MAX_PER_BOOK = 20


def _summarize_revision(prev: Optional[dict], curr: dict) -> str:
    """One-line summary of what changed compared to the previous revision."""
    if not prev:
        return "Initial save"
    parts: List[str] = []
    if prev.get("title") != curr.get("title"):
        parts.append("title")
    if prev.get("author") != curr.get("author"):
        parts.append("author")
    if prev.get("page_size") != curr.get("page_size"):
        parts.append("page size")
    if bool(prev.get("is_chapter_book")) != bool(curr.get("is_chapter_book")):
        parts.append("chapter mode")
    if prev.get("text_presets") != curr.get("text_presets"):
        parts.append("text presets")
    prev_pages = prev.get("pages") or []
    curr_pages = curr.get("pages") or []
    if len(prev_pages) != len(curr_pages):
        delta = len(curr_pages) - len(prev_pages)
        parts.append(f"{abs(delta)} page{'s' if abs(delta) != 1 else ''} {'added' if delta > 0 else 'removed'}")
    else:
        # Per-page block deltas
        block_changes = 0
        for p_old, p_new in zip(prev_pages, curr_pages):
            old_blocks = p_old.get("blocks") or []
            new_blocks = p_new.get("blocks") or []
            if len(old_blocks) != len(new_blocks) or any(
                ob.get("id") != nb.get("id") or ob.get("html") != nb.get("html") or
                ob.get("x") != nb.get("x") or ob.get("y") != nb.get("y") or
                ob.get("width") != nb.get("width") or ob.get("height") != nb.get("height")
                for ob, nb in zip(old_blocks, new_blocks)
            ):
                block_changes += 1
        if block_changes:
            parts.append(f"{block_changes} page{'s' if block_changes != 1 else ''} edited")
    return ", ".join(parts) if parts else "Minor change"


async def _maybe_snapshot(book_doc: dict):
    """Snapshot the book to book_revisions if the last revision is older than
    REVISION_DEBOUNCE_SECONDS (or none exists). Trim to REVISION_MAX_PER_BOOK."""
    book_id = book_doc["id"]
    latest = await db.book_revisions.find(
        {"book_id": book_id}, {"_id": 0}
    ).sort("created_at", -1).limit(1).to_list(1)
    if latest:
        try:
            last_ts = datetime.fromisoformat(latest[0]["created_at"])
            now_ts = datetime.now(timezone.utc)
            if (now_ts - last_ts).total_seconds() < REVISION_DEBOUNCE_SECONDS:
                return  # within debounce window; skip
            prev_doc = latest[0]
        except Exception:
            prev_doc = latest[0]
    else:
        prev_doc = None
    summary = _summarize_revision(prev_doc, book_doc)
    revision = BookRevision(
        book_id=book_id,
        title=book_doc.get("title", "Untitled Book"),
        author=book_doc.get("author", ""),
        page_size=book_doc.get("page_size", "a4"),
        page_count=len(book_doc.get("pages") or []),
        pages=[Page(**p) for p in (book_doc.get("pages") or [])],
        page_number_start=book_doc.get("page_number_start", 1),
        is_chapter_book=bool(book_doc.get("is_chapter_book")),
        text_presets=book_doc.get("text_presets"),
        summary=summary,
    )
    await db.book_revisions.insert_one(revision.model_dump())
    # Trim
    all_revs = await db.book_revisions.find(
        {"book_id": book_id}, {"_id": 0, "id": 1, "created_at": 1}
    ).sort("created_at", -1).to_list(1000)
    if len(all_revs) > REVISION_MAX_PER_BOOK:
        to_delete = [r["id"] for r in all_revs[REVISION_MAX_PER_BOOK:]]
        await db.book_revisions.delete_many({"id": {"$in": to_delete}})


# ===== App =====
app = FastAPI()
api_router = APIRouter(prefix="/api")


@app.on_event("startup")
async def startup():
    try:
        init_storage()
        logging.info("Storage initialized")
    except Exception as e:
        logging.error(f"Storage init failed: {e}")
    # Auth: indexes + idempotent admin seed. Must run BEFORE the app starts
    # serving real traffic so the first login request finds the admin row.
    try:
        from auth import ensure_indexes, seed_admin
        await ensure_indexes(db)
        await seed_admin(db)
    except Exception as e:
        logging.error(f"Auth bootstrap failed: {e}")
    # Ensure the pdf_jobs collection has its TTL + lookup indexes.
    try:
        await _ensure_pdf_jobs_indexes()
    except Exception as e:
        logging.warning(f"pdf_jobs index setup deferred: {e}")
    # PDF export requires Chromium, but downloading it (~200 MB, ~20 s) must
    # NEVER block FastAPI's startup — uvicorn's lifespan has a hard timeout
    # and a slow install would leave the entire app unresponsive (book CRUD,
    # asset list, everything). Kick the install off as a background task so
    # the API answers requests immediately; the PDF endpoint waits on the
    # same task lazily.
    import asyncio as _asyncio
    from pdf_builder import ensure_chromium_installed

    async def _bg_install():
        try:
            await ensure_chromium_installed()
        except Exception as e:
            logging.warning(f"Chromium background install failed (will retry on first PDF request): {e}")

    _asyncio.create_task(_bg_install())


@app.on_event("shutdown")
async def shutdown_db_client():
    client.close()


# ===== Routes =====
@api_router.get("/")
async def root():
    return {"message": "Book Template API"}


@api_router.post("/books", response_model=Book)
async def create_book(payload: BookCreate):
    # Start with one blank page
    book = Book(
        title=payload.title or "Untitled Book",
        author=payload.author or "",
        page_size=payload.page_size or "a4",
        pages=[Page()],
    )
    doc = book.model_dump()
    await db.books.insert_one(doc)
    return book


@api_router.post("/books/import", response_model=Book)
async def import_book(
    file: UploadFile = File(...),
    title: Optional[str] = Form(None),
    author: Optional[str] = Form(None),
    page_size: str = Form("a4"),
):
    """Create a new book from an uploaded manuscript (.docx, .md, .txt).
    Smart-splits the document into pages and pre-populates each page with
    a centered text block leaving the bottom half empty for an illustration."""
    from book_importer import (
        parse_manuscript,
        chunks_to_pages,
        derive_title_and_author,
    )

    if page_size not in {"a4", "letter", "square", "book6x9"}:
        page_size = "a4"

    data = await file.read()
    # Cap manuscript size — same ceiling as the image uploader.
    if len(data) > 10 * 1024 * 1024:
        raise HTTPException(413, "File too large (max 10MB)")
    try:
        chunks = parse_manuscript(file.filename or "", data)
    except ValueError as e:
        raise HTTPException(400, str(e))
    except Exception as e:
        logging.exception("Manuscript parsing failed")
        raise HTTPException(400, f"Could not parse manuscript: {e}")

    derived_title, derived_author = derive_title_and_author(chunks)
    pages_data = chunks_to_pages(chunks, page_size_key=page_size)

    book = Book(
        title=(title or derived_title or "Untitled Book").strip()[:200],
        author=(author or derived_author or "").strip()[:200],
        page_size=page_size,
        pages=[Page(**p) for p in pages_data],
    )
    await db.books.insert_one(book.model_dump())
    return book


@api_router.get("/books", response_model=List[BookSummary])
async def list_books():
    books = await db.books.find({}, {"_id": 0}).sort("updated_at", -1).to_list(1000)
    summaries: List[BookSummary] = []
    for b in books:
        cover_url = None
        cover_page_obj: Optional[Page] = None
        pages = b.get("pages") or []
        if pages:
            try:
                cover_page_obj = Page(**pages[0])
            except Exception:
                cover_page_obj = None
            for blk in pages[0].get("blocks", []) or []:
                if blk.get("type") == "image" and blk.get("image_url"):
                    cover_url = blk["image_url"]
                    break
        summaries.append(
            BookSummary(
                id=b["id"],
                title=b.get("title", "Untitled Book"),
                author=b.get("author", ""),
                page_size=b.get("page_size", "a4"),
                page_count=len(pages),
                created_at=b.get("created_at", _now_iso()),
                updated_at=b.get("updated_at", _now_iso()),
                cover_image_url=cover_url,
                cover_page=cover_page_obj,
            )
        )
    return summaries


@api_router.get("/books/{book_id}", response_model=Book)
async def get_book(book_id: str):
    doc = await db.books.find_one({"id": book_id}, {"_id": 0})
    if not doc:
        raise HTTPException(404, "Book not found")
    return Book(**doc)


@api_router.put("/books/{book_id}", response_model=Book)
async def update_book(book_id: str, payload: BookUpdate):
    existing = await db.books.find_one({"id": book_id}, {"_id": 0})
    if not existing:
        raise HTTPException(404, "Book not found")
    update_data = {k: v for k, v in payload.model_dump(exclude_unset=True).items() if v is not None}
    if "pages" in update_data:
        # Validate via Page model
        update_data["pages"] = [Page(**p).model_dump() if not isinstance(p, dict) or "id" not in p else Page(**p).model_dump() for p in update_data["pages"]]
    update_data["updated_at"] = _now_iso()
    await db.books.update_one({"id": book_id}, {"$set": update_data})
    doc = await db.books.find_one({"id": book_id}, {"_id": 0})
    # Audit-log: snapshot if last revision is older than the debounce window.
    try:
        await _maybe_snapshot(doc)
    except Exception as e:
        logging.warning(f"Revision snapshot failed for {book_id}: {e}")
    return Book(**doc)


@api_router.get("/books/{book_id}/revisions", response_model=List[BookRevisionSummary])
async def list_revisions(book_id: str):
    book = await db.books.find_one({"id": book_id}, {"_id": 0})
    if not book:
        raise HTTPException(404, "Book not found")
    revs = await db.book_revisions.find(
        {"book_id": book_id}, {"_id": 0}
    ).sort("created_at", -1).to_list(REVISION_MAX_PER_BOOK)
    return [
        BookRevisionSummary(
            id=r["id"],
            book_id=r["book_id"],
            created_at=r["created_at"],
            title=r.get("title", "Untitled Book"),
            page_count=r.get("page_count", 0),
            summary=r.get("summary", ""),
        )
        for r in revs
    ]


@api_router.post("/books/{book_id}/revisions/{revision_id}/restore", response_model=Book)
async def restore_revision(book_id: str, revision_id: str):
    rev = await db.book_revisions.find_one({"id": revision_id, "book_id": book_id}, {"_id": 0})
    if not rev:
        raise HTTPException(404, "Revision not found")
    update_data = {
        "title": rev.get("title", "Untitled Book"),
        "author": rev.get("author", ""),
        "page_size": rev.get("page_size", "a4"),
        "page_number_start": rev.get("page_number_start", 1),
        "is_chapter_book": bool(rev.get("is_chapter_book")),
        "text_presets": rev.get("text_presets"),
        "pages": [Page(**p).model_dump() for p in (rev.get("pages") or [])],
        "updated_at": _now_iso(),
    }
    res = await db.books.update_one({"id": book_id}, {"$set": update_data})
    if res.matched_count == 0:
        raise HTTPException(404, "Book not found")
    doc = await db.books.find_one({"id": book_id}, {"_id": 0})
    # The restore itself is a meaningful event — snapshot immediately, bypassing
    # the debounce window so the user always has a "before restore" checkpoint.
    try:
        snap = BookRevision(
            book_id=book_id,
            title=doc.get("title", "Untitled Book"),
            author=doc.get("author", ""),
            page_size=doc.get("page_size", "a4"),
            page_count=len(doc.get("pages") or []),
            pages=[Page(**p) for p in (doc.get("pages") or [])],
            page_number_start=doc.get("page_number_start", 1),
            is_chapter_book=bool(doc.get("is_chapter_book")),
            text_presets=doc.get("text_presets"),
            summary=f"Restored from {rev.get('created_at', '')[:19].replace('T', ' ')}",
        )
        await db.book_revisions.insert_one(snap.model_dump())
    except Exception as e:
        logging.warning(f"Post-restore snapshot failed: {e}")
    return Book(**doc)


@api_router.get("/books/{book_id}/export.pdf")
async def export_book_pdf(book_id: str, request: Request):
    """Synchronous PDF export — kept for direct/script use. Browsers should
    prefer the job-based flow (`/export/start` → `/export/status` →
    `/export/download`) which is resilient to proxy/CDN response timeouts on
    custom domains."""
    from pdf_builder import build_book_pdf  # local import keeps startup snappy

    book = await db.books.find_one({"id": book_id}, {"_id": 0})
    if not book:
        raise HTTPException(404, "Book not found")
    # Compute the public base URL from the incoming request so Chromium can
    # fall back to fetching images directly when the internal object-storage
    # path fails (the editor proves the public route works from the browser).
    base_url = str(request.base_url).rstrip("/")
    try:
        pdf_bytes = await build_book_pdf(book, get_object, public_base_url=base_url)
    except Exception as e:
        logging.exception("PDF build failed")
        raise HTTPException(500, f"PDF build failed: {e}")
    safe = re.sub(r"[^A-Za-z0-9._-]+", "_", book.get("title") or "book").strip("_") or "book"
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{safe}.pdf"'},
    )


# ===== PDF export — job-based flow =====
# Job state must be SHARED across backend pods (production runs multiple
# replicas behind a load balancer — a job created on pod A must be
# pollable from pod B). We store status in MongoDB and the PDF bytes in
# object storage, the same way we handle book images.
_PDF_JOB_TTL_SECONDS = 30 * 60  # auto-expire stale jobs after 30 min
_PDF_OBJECT_PREFIX = "booktemplate/pdfjobs"


async def _ensure_pdf_jobs_indexes() -> None:
    """Create the TTL index once so finished jobs auto-purge from Mongo."""
    try:
        await db.pdf_jobs.create_index(
            "expires_at", expireAfterSeconds=0, name="pdf_jobs_ttl"
        )
        await db.pdf_jobs.create_index("job_id", unique=True, name="pdf_jobs_job_id")
    except Exception as e:
        logging.warning(f"pdf_jobs index creation failed (probably already exists): {e}")


async def _run_pdf_job(
    job_id: str,
    book_id: str,
    base_url: str,
    start_page: Optional[int] = None,
    end_page: Optional[int] = None,
    pdfx: bool = False,
    cover_spread: bool = False,
    spine_width_in: Optional[float] = None,
) -> None:
    """Background worker — builds the PDF, uploads bytes to object storage,
    flips the Mongo record to `ready` (or `failed`).

    `start_page` / `end_page` are 1-indexed INCLUSIVE. When provided, only
    those pages are rendered (the full book is loaded then the `pages` list
    is sliced before handing it to the builder — keeps page-numbering logic
    on the builder side simple: it always sees a contiguous `pages` array).

    `pdfx` runs the final PDF through Ghostscript to produce a print-ready
    PDF/X-1a:2001 file (CMYK, embedded fonts, transparency flattened,
    OutputIntent ICC profile baked in). Adds ~10–30s to export time.
    """
    from pdf_builder import build_book_pdf

    # Per-job stage tracker. Each call writes to Mongo so the polling client
    # can show "rendering chunk 3/8" instead of just an elapsed counter.
    # We coalesce updates so a callback storm doesn't hammer Mongo.
    last_stage: dict = {"v": None}

    class _Cancelled(Exception):
        """Raised by `_check_cancelled` when the user has clicked Cancel on
        the export toast. The except clause in the main worker catches it
        and flips the job to failed with a clean 'Cancelled by user'
        message — and crucially stops further Playwright/Ghostscript work
        so the pod's resources are freed immediately."""

    async def _check_cancelled() -> None:
        """Called at every coarse checkpoint in the main flow (between
        chunks, between major stages). Mongo round-trip is sub-ms locally
        so this is cheap. We avoid calling it from `_on_stage` because
        that's a sync callback executed from inside synchronous render
        code — we can't await there."""
        doc = await db.pdf_jobs.find_one(
            {"job_id": job_id}, {"_id": 0, "cancel_requested": 1}
        )
        if doc and doc.get("cancel_requested"):
            raise _Cancelled()

    def _on_stage(stage: str) -> None:
        if stage == last_stage["v"]:
            return
        last_stage["v"] = stage
        # Fire-and-forget; failures here must never break the render.
        # `ensure_future` accepts both coroutines and Motor's Future-like
        # objects (motor wraps Mongo ops in chained asyncio Futures, which
        # `create_task` rejects).
        asyncio.ensure_future(db.pdf_jobs.update_one(
            {"job_id": job_id},
            {"$set": {"stage": stage, "stage_at": _now_iso()}},
        ))

    try:
        book = await db.books.find_one({"id": book_id}, {"_id": 0})
        if not book:
            await db.pdf_jobs.update_one(
                {"job_id": job_id},
                {"$set": {"status": "failed", "error": "Book not found",
                          "finished_at": _now_iso()}},
            )
            return
        # Range bookkeeping. We do NOT slice `book["pages"]` here — the
        # builder needs the FULL array so it can preserve original page
        # numbers and original-length-based cover detection. We just clamp
        # the user-supplied range against the actual book length and pass
        # it down for the builder to slice internally.
        all_pages = book.get("pages") or []
        total = len(all_pages)
        applied_start = start_page if start_page is not None else 1
        applied_end = end_page if end_page is not None else total
        applied_start = max(1, min(applied_start, total))
        applied_end = max(applied_start, min(applied_end, total))
        is_range = start_page is not None or end_page is not None

        _on_stage("starting")
        await _check_cancelled()
        if cover_spread:
            # Cover spread overrides any range — by definition it builds
            # the cover ONLY, using pages[0] and pages[-1].
            from pdf_builder import build_cover_spread_pdf
            pdf_bytes = await build_cover_spread_pdf(
                book, get_object, public_base_url=base_url, progress_cb=_on_stage,
                spine_width_in=spine_width_in,
            )
        else:
            pdf_bytes = await build_book_pdf(
                book, get_object, public_base_url=base_url, progress_cb=_on_stage,
                start_page=applied_start if is_range else None,
                end_page=applied_end if is_range else None,
                pdfx_bleed=pdfx,
            )
        # Post-process to PDF/X-1a (CMYK, embedded fonts, OutputIntent) if
        # the caller requested a print-ready file. Runs only when the toggle
        # is on — for everyday previewing the raw RGB PDF is much faster.
        if pdfx:
            from pdfx_converter import convert_to_pdfx
            from pypdf import PdfReader
            from io import BytesIO
            # Read the page count out of the PDF we just rendered so the
            # streaming progress bar below has a denominator to count
            # against ("converting to PDF/X-1a (12/60)").
            try:
                total_pages_pdfx = len(PdfReader(BytesIO(pdf_bytes)).pages)
            except Exception:
                total_pages_pdfx = None
            await _check_cancelled()
            _on_stage("converting to PDF/X-1a")
            pdf_bytes = await convert_to_pdfx(
                pdf_bytes,
                title=book.get("title") or "book",
                total_pages=total_pages_pdfx,
                progress_cb=_on_stage,
            )
        await _check_cancelled()
        safe = re.sub(r"[^A-Za-z0-9._-]+", "_", book.get("title") or "book").strip("_") or "book"
        # Filename includes the range when partial so users get distinct
        # downloads on disk: "MyBook_pp_1-50.pdf" / "MyBook_pp_51-112.pdf".
        # "_pdfx" suffix makes print-ready exports unmistakable in Finder.
        pdfx_suffix = "_pdfx" if pdfx else ""
        if cover_spread:
            # IngramSpark-style filename hint — "_cov" matches their
            # cover-file naming convention (`isbn_cov.pdf`).
            filename = f"{safe}_cov{pdfx_suffix}.pdf"
        else:
            filename = (
                f"{safe}_pp_{applied_start}-{applied_end}{pdfx_suffix}.pdf"
                if is_range else f"{safe}{pdfx_suffix}.pdf"
            )
        # Upload PDF bytes to shared object storage so any pod can serve them.
        _on_stage("uploading")
        object_path = f"{_PDF_OBJECT_PREFIX}/{job_id}.pdf"
        await asyncio.to_thread(put_object, object_path, pdf_bytes, "application/pdf")
        await db.pdf_jobs.update_one(
            {"job_id": job_id},
            {"$set": {
                "status": "ready",
                "stage": "ready",
                "size": len(pdf_bytes),
                "filename": filename,
                "start_page": applied_start,
                "end_page": applied_end,
                "object_path": object_path,
                "finished_at": _now_iso(),
            }},
        )
    except _Cancelled:
        # User clicked the X on the export toast. Flip the job to a clean
        # 'failed' state with a friendly reason — the frontend special-
        # cases this string to show "Export cancelled" instead of the
        # alarming red error toast.
        logging.info("PDF job %s cancelled by user", job_id)
        await db.pdf_jobs.update_one(
            {"job_id": job_id},
            {"$set": {"status": "failed",
                      "error": "Cancelled by user",
                      "finished_at": _now_iso()}},
        )
    except Exception as e:
        # Capture a snippet of the traceback so the client toast can show
        # something more useful than a generic "build failed". Truncate
        # heavily — the full trace is in logs, the toast just needs a hint.
        import traceback
        tb = traceback.format_exc().splitlines()
        last_lines = " | ".join(tb[-3:]) if tb else ""
        logging.exception("PDF job %s failed", job_id)
        await db.pdf_jobs.update_one(
            {"job_id": job_id},
            {"$set": {"status": "failed",
                      "error": f"{e}".strip()[:300] or "PDF build failed",
                      "trace": last_lines[:500],
                      "finished_at": _now_iso()}},
        )


class PdfJobStartRequest(BaseModel):
    """Optional 1-indexed inclusive page range. Both omitted = full book.
    `pdfx=true` runs the final PDF through Ghostscript to produce a
    PDF/X-1a:2001-compliant CMYK file ready for commercial printing.
    `cover_spread=true` builds a print-ready cover spread PDF (back +
    spine + front, with 0.125" bleed all around) instead of the
    interior. `spine_width_in` overrides the auto-computed spine width
    when the user knows their printer's paper caliper exactly."""
    model_config = ConfigDict(extra="ignore")
    start_page: Optional[int] = None
    end_page: Optional[int] = None
    pdfx: bool = False
    cover_spread: bool = False
    spine_width_in: Optional[float] = None


@api_router.post("/books/{book_id}/pdf-jobs")
async def export_pdf_start(
    book_id: str,
    request: Request,
    payload: Optional[PdfJobStartRequest] = None,
):
    """Kick off a background PDF build. Returns a job_id the client polls.
    Each call returns in ~milliseconds — no risk of proxy/CDN timeouts.

    Optional `start_page` / `end_page` (1-indexed, inclusive) export a
    contiguous slice — used by the editor's "Export range" UI to ship a
    100+ page book as several smaller PDFs that can be stitched externally.

    Note: route path deliberately avoids `.pdf` in it because some CDNs/edge
    proxies treat URLs containing `.pdf` as static-file requests and may
    short-circuit them with 404 before they reach the backend.
    """
    # Sanity-check the book exists before we spawn a worker (so the client
    # gets a 404 immediately rather than a "failed" status 20s later).
    book = await db.books.find_one({"id": book_id}, {"_id": 0, "pages": 1})
    if not book:
        raise HTTPException(404, "Book not found")
    total_pages = len(book.get("pages") or [])

    start_page = payload.start_page if payload else None
    end_page = payload.end_page if payload else None
    pdfx = bool(payload.pdfx) if payload else False
    cover_spread = bool(payload.cover_spread) if payload else False
    spine_width_in = payload.spine_width_in if payload else None
    # Cover spread always overrides any explicit page range — the cover
    # is, by definition, only pages[0] + pages[-1].
    if cover_spread:
        start_page = None
        end_page = None
    if start_page is not None or end_page is not None:
        if start_page is None or end_page is None:
            raise HTTPException(400, "start_page and end_page must be provided together")
        if not isinstance(start_page, int) or not isinstance(end_page, int):
            raise HTTPException(400, "start_page and end_page must be integers")
        if start_page < 1 or end_page < 1:
            raise HTTPException(400, "Page numbers are 1-indexed")
        if start_page > end_page:
            raise HTTPException(400, "start_page must be <= end_page")
        if start_page > total_pages:
            raise HTTPException(400, f"start_page exceeds book length ({total_pages})")
        # end_page > total is allowed — we clamp to total_pages in the worker.

    job_id = str(uuid.uuid4())
    now = datetime.now(timezone.utc)
    await db.pdf_jobs.insert_one({
        "job_id": job_id,
        "book_id": book_id,
        "status": "pending",
        "start_page": start_page,
        "end_page": end_page,
        "pdfx": pdfx,
        "cover_spread": cover_spread,
        "spine_width_in": spine_width_in,
        "created_at": now.isoformat(),
        # Mongo TTL index uses a real Date — not an ISO string.
        "expires_at": now + timedelta(seconds=_PDF_JOB_TTL_SECONDS),
    })
    asyncio.create_task(_run_pdf_job(
        job_id, book_id, str(request.base_url).rstrip("/"),
        start_page=start_page, end_page=end_page, pdfx=pdfx,
        cover_spread=cover_spread, spine_width_in=spine_width_in,
    ))
    return {"job_id": job_id, "status": "pending"}


@api_router.get("/books/{book_id}/pdf-jobs/{job_id}")
async def export_pdf_status(book_id: str, job_id: str):
    job = await db.pdf_jobs.find_one(
        {"job_id": job_id, "book_id": book_id}, {"_id": 0}
    )
    if not job:
        raise HTTPException(404, "Job not found")
    resp = {
        "status": job["status"],
        "created_at": job["created_at"],
        "stage": job.get("stage"),
    }
    if job["status"] == "ready":
        resp["size"] = job.get("size", 0)
        resp["filename"] = job.get("filename", "book.pdf")
        resp["start_page"] = job.get("start_page")
        resp["end_page"] = job.get("end_page")
    elif job["status"] == "failed":
        resp["error"] = job.get("error") or "PDF build failed"
        if job.get("trace"):
            resp["trace"] = job["trace"]
    if job.get("cancel_requested"):
        # Surface the user's cancel intent even if the worker hasn't
        # noticed yet — the frontend uses this to stop polling at the
        # next tick rather than waiting for the worker to flip to failed.
        resp["cancel_requested"] = True
    return resp


@api_router.post("/books/{book_id}/pdf-jobs/{job_id}/cancel")
async def cancel_pdf_job(book_id: str, job_id: str):
    """Mark a still-pending PDF job as cancelled. The worker checks this
    flag at every stage tick and bails out (raising a cancellation
    error that flips the job to `failed` with a clean message). Already
    finished jobs are a no-op — the response still returns 200 so the
    caller doesn't need to distinguish."""
    job = await db.pdf_jobs.find_one(
        {"job_id": job_id, "book_id": book_id}, {"_id": 0, "status": 1}
    )
    if not job:
        raise HTTPException(404, "Job not found")
    if job["status"] != "pending":
        return {"cancel_requested": False, "status": job["status"]}
    await db.pdf_jobs.update_one(
        {"job_id": job_id, "book_id": book_id},
        {"$set": {"cancel_requested": True}},
    )
    return {"cancel_requested": True, "status": "pending"}


@api_router.get("/books/{book_id}/pdf-jobs/{job_id}/download")
async def export_pdf_download(book_id: str, job_id: str):
    job = await db.pdf_jobs.find_one(
        {"job_id": job_id, "book_id": book_id}, {"_id": 0}
    )
    if not job:
        raise HTTPException(404, "Job not found")
    if job["status"] != "ready":
        raise HTTPException(409, f"Job is {job['status']}, not ready for download")
    object_path = job.get("object_path")
    filename = job.get("filename", "book.pdf")
    if not object_path:
        raise HTTPException(500, "Job is ready but has no storage path")
    try:
        pdf_bytes, _ = await asyncio.to_thread(get_object, object_path)
    except Exception as e:
        logging.exception("PDF download fetch failed")
        raise HTTPException(500, f"PDF retrieval failed: {e}")
    # Persist an export-history record BEFORE deleting the job, so the
    # editor's "Export" popover can show which page ranges have already
    # been delivered. Failure to record must not fail the download itself —
    # users care about getting their PDF more than the bookkeeping.
    try:
        await db.book_exports.insert_one({
            "id": str(uuid.uuid4()),
            "book_id": book_id,
            "filename": filename,
            "size": job.get("size", len(pdf_bytes)),
            "start_page": job.get("start_page"),
            "end_page": job.get("end_page"),
            "exported_at": _now_iso(),
        })
    except Exception:
        logging.exception("Failed to record export history for job %s", job_id)
    # Consume the job: drop the Mongo record so the user can't re-download by
    # replaying the URL. (Object storage entry expires via the TTL anyway.)
    await db.pdf_jobs.delete_one({"job_id": job_id})
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@api_router.get("/books/{book_id}/exports")
async def list_book_exports(book_id: str):
    """Returns the export history for a book, newest first. Used by the
    editor's "Export PDF" popover to show which page ranges have already
    been downloaded — so users assembling a big book in chunks don't
    duplicate work."""
    docs = await db.book_exports.find(
        {"book_id": book_id},
        {"_id": 0},
    ).sort("exported_at", -1).to_list(200)
    return docs


@api_router.delete("/books/{book_id}/exports/{export_id}")
async def delete_book_export(book_id: str, export_id: str):
    res = await db.book_exports.delete_one({"id": export_id, "book_id": book_id})
    if res.deleted_count == 0:
        raise HTTPException(404, "Export record not found")
    return {"deleted": True}


@api_router.get("/pdf-health")
async def pdf_health():
    """Diagnostic endpoint — reports everything the PDF pipeline depends on
    so we can pinpoint production failures without a redeploy. Safe to
    expose: contains no secrets, just paths/counts/booleans."""
    from pdf_builder import (
        _autodetect_chromium_path,
        _chromium_ready,
        _try_launch_chromium,
    )

    info: dict[str, Any] = {
        "playwright_browsers_path_env": os.environ.get("PLAYWRIGHT_BROWSERS_PATH"),
        "detected_browsers_path": _autodetect_chromium_path(),
        "chromium_ready_cached": _chromium_ready,
        "python": f"{__import__('sys').version_info.major}.{__import__('sys').version_info.minor}",
    }
    # Live launch probe — the cached flag can lie if the binary was wiped.
    try:
        info["chromium_launchable"] = await _try_launch_chromium()
    except Exception as e:
        info["chromium_launchable"] = False
        info["chromium_launch_error"] = str(e)[:300]

    # Disk + memory snapshot (helps identify OOM/disk-full failures).
    try:
        import shutil
        du = shutil.disk_usage("/")
        info["disk_total_mb"] = du.total // (1024 * 1024)
        info["disk_free_mb"] = du.free // (1024 * 1024)
    except Exception as e:
        info["disk_error"] = str(e)[:200]
    try:
        # /proc/meminfo is always present on Linux containers and avoids
        # pulling in psutil just for diagnostics.
        with open("/proc/meminfo") as f:
            mem: dict[str, int] = {}
            for line in f:
                parts = line.split()
                if len(parts) >= 2 and parts[0].rstrip(":") in {
                    "MemTotal", "MemAvailable", "MemFree", "SwapTotal", "SwapFree"
                }:
                    mem[parts[0].rstrip(":")] = int(parts[1]) // 1024  # kB → MB
            info["memory_mb"] = mem
    except Exception as e:
        info["memory_error"] = str(e)[:200]

    # Recent failed jobs (last 5) — fastest way to see what's been blowing up.
    try:
        recent = await db.pdf_jobs.find(
            {"status": "failed"}, {"_id": 0, "job_id": 1, "book_id": 1,
                                    "error": 1, "stage": 1, "finished_at": 1},
        ).sort("finished_at", -1).to_list(5)
        info["recent_failures"] = recent
    except Exception as e:
        info["recent_failures_error"] = str(e)[:200]

    # Recent in-flight jobs (last 5 pending) — shows what's stuck.
    try:
        pending = await db.pdf_jobs.find(
            {"status": "pending"}, {"_id": 0, "job_id": 1, "book_id": 1,
                                     "stage": 1, "created_at": 1, "stage_at": 1},
        ).sort("created_at", -1).to_list(5)
        info["pending_jobs"] = pending
    except Exception as e:
        info["pending_jobs_error"] = str(e)[:200]

    return info




@api_router.post("/books/{book_id}/duplicate", response_model=Book)
async def duplicate_book(book_id: str):
    src = await db.books.find_one({"id": book_id}, {"_id": 0})
    if not src:
        raise HTTPException(404, "Book not found")
    new_pages: List[Page] = []
    for p in src.get("pages", []):
        page_obj = Page(**p)
        page_obj.id = str(uuid.uuid4())
        new_blocks: List[Block] = []
        for b in page_obj.blocks:
            block_obj = Block(**b.model_dump())
            block_obj.id = str(uuid.uuid4())
            new_blocks.append(block_obj)
        page_obj.blocks = new_blocks
        new_pages.append(page_obj)
    copy = Book(
        title=f"{src.get('title', 'Untitled Book')} (copy)",
        author=src.get("author", ""),
        page_size=src.get("page_size", "a4"),
        text_presets=src.get("text_presets"),
        pages=new_pages,
    )
    await db.books.insert_one(copy.model_dump())
    # Clone asset records (point to same storage paths) so the duplicate's
    # Assets panel mirrors the original book's library.
    src_assets = await db.files.find({"book_id": book_id, "is_deleted": False}).to_list(2000)
    for a in src_assets:
        await db.files.insert_one({
            "id": str(uuid.uuid4()),
            "storage_path": a["storage_path"],
            "original_filename": a.get("original_filename"),
            "content_type": a.get("content_type"),
            "size": a.get("size"),
            "is_deleted": False,
            "created_at": _now_iso(),
            "book_id": copy.id,
        })
    return copy


@api_router.delete("/books/{book_id}")
async def delete_book(book_id: str):
    res = await db.books.delete_one({"id": book_id})
    if res.deleted_count == 0:
        raise HTTPException(404, "Book not found")
    # Soft-delete asset records scoped to this book so they no longer surface
    # in any asset panel (other books are unaffected — assets are now book-scoped).
    await db.files.update_many({"book_id": book_id}, {"$set": {"is_deleted": True}})
    # Drop export-history records — the book is gone, the history is meaningless.
    await db.book_exports.delete_many({"book_id": book_id})
    return {"deleted": True}


@api_router.get("/templates", response_model=List[Template])
async def list_templates():
    docs = await db.templates.find({}, {"_id": 0}).sort("created_at", -1).to_list(500)
    return [Template(**d) for d in docs]


@api_router.post("/templates", response_model=Template)
async def create_template(payload: TemplateCreate):
    template = Template(
        name=payload.name,
        page_size=payload.page_size,
        cover=payload.cover,
        interior=payload.interior,
        back_cover=payload.back_cover,
        text_presets=payload.text_presets,
    )
    await db.templates.insert_one(template.model_dump())
    return template


@api_router.delete("/templates/{template_id}")
async def delete_template(template_id: str):
    res = await db.templates.delete_one({"id": template_id})
    if res.deleted_count == 0:
        raise HTTPException(404, "Template not found")
    return {"deleted": True}




@api_router.post("/upload")
async def upload_image(file: UploadFile = File(...), book_id: Optional[str] = Form(None)):
    ext = (file.filename or "bin").rsplit(".", 1)[-1].lower() if "." in (file.filename or "") else "bin"
    content_type = file.content_type or MIME_TYPES.get(ext, "application/octet-stream")
    if not content_type.startswith("image/"):
        raise HTTPException(400, "Only image uploads are supported")
    path = f"{APP_NAME}/uploads/{uuid.uuid4()}.{ext}"
    data = await file.read()
    if len(data) > 10 * 1024 * 1024:
        raise HTTPException(413, "File too large (max 10MB)")
    result = put_object(path, data, content_type)
    canonical_path = result["path"]
    await db.files.insert_one({
        "id": str(uuid.uuid4()),
        "storage_path": canonical_path,
        "original_filename": file.filename,
        "content_type": content_type,
        "size": result.get("size", len(data)),
        "is_deleted": False,
        "created_at": _now_iso(),
        "book_id": book_id,
    })
    return {
        "path": canonical_path,
        "url": f"/api/files/{canonical_path}",
        "content_type": content_type,
        "size": result.get("size", len(data)),
    }


class GenerateAssetRequest(BaseModel):
    prompt: str
    book_id: Optional[str] = None


@api_router.post("/assets/generate")
async def generate_asset(req: GenerateAssetRequest):
    """Generate an illustration with Gemini Nano Banana and persist it
    to object storage as a regular asset — so the user can immediately
    drag it onto a page from the same Assets panel."""
    import base64
    from emergentintegrations.llm.chat import LlmChat, UserMessage

    prompt = (req.prompt or "").strip()
    if not prompt:
        raise HTTPException(400, "Prompt is required")
    if len(prompt) > 2000:
        raise HTTPException(400, "Prompt is too long (max 2000 chars)")
    if not EMERGENT_KEY:
        raise HTTPException(500, "Image generation is not configured (missing EMERGENT_LLM_KEY)")

    chat = LlmChat(
        api_key=EMERGENT_KEY,
        session_id=str(uuid.uuid4()),
        system_message="You generate single high-quality illustration images for use in printed books. Produce one image only. Do not add any text overlays or watermarks unless explicitly requested.",
    )
    chat.with_model("gemini", "gemini-3.1-flash-image-preview").with_params(modalities=["image", "text"])

    msg = UserMessage(text=prompt)
    try:
        _text, images = await chat.send_message_multimodal_response(msg)
    except Exception as e:  # network / upstream errors surface to the user
        raise HTTPException(502, f"Image generation failed: {e}")

    if not images:
        raise HTTPException(502, "The model returned no image. Try refining your prompt.")

    img = images[0]
    mime = img.get("mime_type") or "image/png"
    ext = "png" if "png" in mime else "jpg"
    try:
        image_bytes = base64.b64decode(img["data"])
    except Exception:
        raise HTTPException(502, "The model returned a malformed image")

    storage_path = f"{APP_NAME}/uploads/{uuid.uuid4()}.{ext}"
    result = await asyncio.to_thread(put_object, storage_path, image_bytes, mime)
    canonical_path = result.get("path", storage_path)

    # Use the first 60 chars of the prompt as a readable filename so the
    # asset is searchable in the panel.
    pretty_name = (prompt[:60].rstrip() + ("…" if len(prompt) > 60 else "")) + f".{ext}"
    await db.files.insert_one({
        "id": str(uuid.uuid4()),
        "storage_path": canonical_path,
        "original_filename": pretty_name,
        "content_type": mime,
        "size": result.get("size", len(image_bytes)),
        "is_deleted": False,
        "created_at": _now_iso(),
        "book_id": req.book_id,
        "source": "ai_generated",
        "ai_prompt": prompt,
    })
    return {
        "path": canonical_path,
        "url": f"/api/files/{canonical_path}",
        "content_type": mime,
        "size": result.get("size", len(image_bytes)),
        "original_filename": pretty_name,
        "source": "ai_generated",
    }


@api_router.get("/assets")
async def list_assets(book_id: Optional[str] = None):
    query: dict = {"is_deleted": False}
    if book_id:
        query["book_id"] = book_id
    docs = await db.files.find(
        query,
        {"_id": 0, "id": 1, "storage_path": 1, "original_filename": 1, "content_type": 1, "size": 1, "created_at": 1, "book_id": 1},
    ).sort("created_at", -1).to_list(2000)
    return [
        {
            "id": d["id"],
            "path": d["storage_path"],
            "url": f"/api/files/{d['storage_path']}",
            "original_filename": d.get("original_filename"),
            "content_type": d.get("content_type"),
            "size": d.get("size"),
            "created_at": d.get("created_at"),
            "book_id": d.get("book_id"),
        }
        for d in docs
    ]


@api_router.delete("/assets/{asset_id}")
async def delete_asset(asset_id: str):
    res = await db.files.update_one(
        {"id": asset_id, "is_deleted": False},
        {"$set": {"is_deleted": True}},
    )
    if res.matched_count == 0:
        raise HTTPException(404, "Asset not found")
    return {"deleted": True}


@api_router.post("/assets/{asset_id}/replace")
async def replace_asset(asset_id: str, file: UploadFile = File(...)):
    """Overwrite an existing asset's bytes in-place. The asset's
    `storage_path` and DB id are preserved, so every block in every book
    that references this asset's URL keeps working without a single edit
    to canvas. This is the recovery path for orphaned assets — e.g. DB
    records migrated between environments while the object-storage
    buckets weren't kept in sync."""
    record = await db.files.find_one({"id": asset_id, "is_deleted": False})
    if not record:
        raise HTTPException(404, "Asset not found")

    ext = (file.filename or "bin").rsplit(".", 1)[-1].lower() if "." in (file.filename or "") else "bin"
    content_type = file.content_type or MIME_TYPES.get(ext, "application/octet-stream")
    if not content_type.startswith("image/"):
        raise HTTPException(400, "Only image uploads are supported")
    data = await file.read()
    if len(data) > 10 * 1024 * 1024:
        raise HTTPException(413, "File too large (max 10MB)")

    # Re-upload to the SAME storage path so existing block.image_url
    # references resolve immediately. Object storage PUT is idempotent.
    storage_path = record["storage_path"]
    result = put_object(storage_path, data, content_type)
    await db.files.update_one(
        {"id": asset_id},
        {"$set": {
            "content_type": content_type,
            "size": result.get("size", len(data)),
            "original_filename": file.filename or record.get("original_filename"),
            "replaced_at": _now_iso(),
        }},
    )
    return {
        "id": asset_id,
        "path": storage_path,
        # Cache-bust on the URL so browsers re-fetch the new bytes
        # instead of serving the old 404-cached response.
        "url": f"/api/files/{storage_path}?v={int(datetime.now(timezone.utc).timestamp())}",
        "content_type": content_type,
        "size": result.get("size", len(data)),
    }


@api_router.get("/files/{path:path}")
async def serve_file(path: str):
    record = await db.files.find_one({"storage_path": path, "is_deleted": False})
    if not record:
        raise HTTPException(404, "File not found")
    data, content_type = get_object(path)
    return Response(
        content=data,
        media_type=record.get("content_type", content_type),
        headers={"Cache-Control": "public, max-age=31536000"},
    )


app.include_router(api_router)

# ----- Auth: mount the auth router and add a global guard middleware -----
from auth import build_auth_router, _extract_token, _get_secret, JWT_ALGORITHM
import jwt as _jwt
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.responses import JSONResponse

# Auth endpoints live alongside the rest of the API.
app.include_router(build_auth_router(db), prefix="/api")


# Paths under /api/ that DO NOT require authentication. Everything else
# under /api/ requires a valid access token.
#  - /api/auth/*  — sign-in, refresh, etc. (would be a chicken-and-egg block).
#  - /api/files/* — image bytes referenced by <img src> in the editor and PDF
#                   renderer. Paths are UUID-based so unguessable in practice.
#  - /api/pdf-health — operator diagnostic.
_PUBLIC_API_PREFIXES = ("/api/auth/", "/api/files/")
_PUBLIC_API_EXACT = {"/api/pdf-health"}


class AuthGuardMiddleware(BaseHTTPMiddleware):
    """Rejects any unauthenticated request to /api/* (with a short allow-list).
    Non-/api paths pass through untouched so the React shell can still load
    and show the login screen even without a session."""

    async def dispatch(self, request, call_next):
        path = request.url.path
        if not path.startswith("/api/"):
            return await call_next(request)
        if any(path.startswith(p) for p in _PUBLIC_API_PREFIXES) or path in _PUBLIC_API_EXACT:
            return await call_next(request)
        # CORS preflights ride through — the browser strips Authorization.
        if request.method == "OPTIONS":
            return await call_next(request)
        token = _extract_token(request)
        if not token:
            return JSONResponse({"detail": "Not authenticated"}, status_code=401)
        try:
            payload = _jwt.decode(token, _get_secret(), algorithms=[JWT_ALGORITHM])
        except _jwt.ExpiredSignatureError:
            return JSONResponse({"detail": "Session expired"}, status_code=401)
        except _jwt.InvalidTokenError:
            return JSONResponse({"detail": "Invalid session"}, status_code=401)
        if payload.get("type") != "access":
            return JSONResponse({"detail": "Invalid token type"}, status_code=401)
        # Stash on request.state so handlers can use it without re-decoding.
        request.state.user_id = payload.get("sub")
        request.state.user_email = payload.get("email")
        return await call_next(request)


# CORS must be the OUTERMOST middleware so preflights short-circuit before
# AuthGuard sees them. Starlette runs middlewares in REVERSE order of
# addition (last added = first to run), so add AuthGuard BEFORE CORS.
app.add_middleware(AuthGuardMiddleware)

app.add_middleware(
    CORSMiddleware,
    allow_credentials=True,
    allow_origins=os.environ.get('CORS_ORIGINS', '*').split(','),
    allow_methods=["*"],
    allow_headers=["*"],
)

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)
